name: Manual Server Deploy

on:  # Trigger events for the workflow
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: build and deploy to aws
        run: |
          echo "deploying to ${{ github.event.inputs.name }} environment"
          cd backend && sam build && cd .aws-sam/build/PlaylistyFunction && rm -fr samconfig.toml template.yaml requirements.txt && cd ../../..
          sam deploy --no-fail-on-empty-changeset --no-confirm-changeset --stack-name flatini-api-${{ github.event.inputs.name }} --s3-bucket flatini-api-${{ github.event.inputs.name }}-s3 --s3-prefix flatini --region eu-west-2 --capabilities CAPABILITY_IAM --parameter-overrides ParameterKey=GoogleClientSecret,ParameterValue="${{ secrets.GOOGLE_CLIENT_SECRET }}" ParameterKey=GoogleClientId,ParameterValue="${{ secrets.GOOGLE_CLIENT_ID }}"